// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: internal/protocol/meshchat.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_PACKET_TYPE_UNKNOWN  PacketType = 0
	PacketType_PACKET_TYPE_INIT     PacketType = 1
	PacketType_PACKET_TYPE_RESP     PacketType = 2
	PacketType_PACKET_TYPE_APP_DATA PacketType = 3
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "PACKET_TYPE_UNKNOWN",
		1: "PACKET_TYPE_INIT",
		2: "PACKET_TYPE_RESP",
		3: "PACKET_TYPE_APP_DATA",
	}
	PacketType_value = map[string]int32{
		"PACKET_TYPE_UNKNOWN":  0,
		"PACKET_TYPE_INIT":     1,
		"PACKET_TYPE_RESP":     2,
		"PACKET_TYPE_APP_DATA": 3,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_meshchat_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_internal_protocol_meshchat_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_meshchat_proto_rawDescGZIP(), []int{0}
}

type MeshPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    uint32     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type       PacketType `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.PacketType" json:"type,omitempty"`
	PacketId   []byte     `protobuf:"bytes,3,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Ttl        uint32     `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	SourceNode []byte     `protobuf:"bytes,5,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	DestNode   []byte     `protobuf:"bytes,6,opt,name=dest_node,json=destNode,proto3" json:"dest_node,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*MeshPacket_Init
	//	*MeshPacket_Resp
	//	*MeshPacket_AppData
	Payload isMeshPacket_Payload `protobuf_oneof:"payload"`
}

func (x *MeshPacket) Reset() {
	*x = MeshPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_meshchat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeshPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPacket) ProtoMessage() {}

func (x *MeshPacket) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_meshchat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPacket.ProtoReflect.Descriptor instead.
func (*MeshPacket) Descriptor() ([]byte, []int) {
	return file_internal_protocol_meshchat_proto_rawDescGZIP(), []int{0}
}

func (x *MeshPacket) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MeshPacket) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_TYPE_UNKNOWN
}

func (x *MeshPacket) GetPacketId() []byte {
	if x != nil {
		return x.PacketId
	}
	return nil
}

func (x *MeshPacket) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MeshPacket) GetSourceNode() []byte {
	if x != nil {
		return x.SourceNode
	}
	return nil
}

func (x *MeshPacket) GetDestNode() []byte {
	if x != nil {
		return x.DestNode
	}
	return nil
}

func (m *MeshPacket) GetPayload() isMeshPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *MeshPacket) GetInit() *InitPayload {
	if x, ok := x.GetPayload().(*MeshPacket_Init); ok {
		return x.Init
	}
	return nil
}

func (x *MeshPacket) GetResp() *RespPayload {
	if x, ok := x.GetPayload().(*MeshPacket_Resp); ok {
		return x.Resp
	}
	return nil
}

func (x *MeshPacket) GetAppData() *AppDataPayload {
	if x, ok := x.GetPayload().(*MeshPacket_AppData); ok {
		return x.AppData
	}
	return nil
}

type isMeshPacket_Payload interface {
	isMeshPacket_Payload()
}

type MeshPacket_Init struct {
	Init *InitPayload `protobuf:"bytes,7,opt,name=init,proto3,oneof"`
}

type MeshPacket_Resp struct {
	Resp *RespPayload `protobuf:"bytes,8,opt,name=resp,proto3,oneof"`
}

type MeshPacket_AppData struct {
	AppData *AppDataPayload `protobuf:"bytes,9,opt,name=app_data,json=appData,proto3,oneof"`
}

func (*MeshPacket_Init) isMeshPacket_Payload() {}

func (*MeshPacket_Resp) isMeshPacket_Payload() {}

func (*MeshPacket_AppData) isMeshPacket_Payload() {}

type InitPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EphemeralKey []byte `protobuf:"bytes,1,opt,name=ephemeral_key,json=ephemeralKey,proto3" json:"ephemeral_key,omitempty"`
	Signature    []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *InitPayload) Reset() {
	*x = InitPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_meshchat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPayload) ProtoMessage() {}

func (x *InitPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_meshchat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPayload.ProtoReflect.Descriptor instead.
func (*InitPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_meshchat_proto_rawDescGZIP(), []int{1}
}

func (x *InitPayload) GetEphemeralKey() []byte {
	if x != nil {
		return x.EphemeralKey
	}
	return nil
}

func (x *InitPayload) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RespPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EphemeralKey []byte `protobuf:"bytes,1,opt,name=ephemeral_key,json=ephemeralKey,proto3" json:"ephemeral_key,omitempty"`
	Signature    []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *RespPayload) Reset() {
	*x = RespPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_meshchat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespPayload) ProtoMessage() {}

func (x *RespPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_meshchat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespPayload.ProtoReflect.Descriptor instead.
func (*RespPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_meshchat_proto_rawDescGZIP(), []int{2}
}

func (x *RespPayload) GetEphemeralKey() []byte {
	if x != nil {
		return x.EphemeralKey
	}
	return nil
}

func (x *RespPayload) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type AppDataPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId   []byte `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNum uint64 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	Ciphertext  []byte `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (x *AppDataPayload) Reset() {
	*x = AppDataPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_meshchat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDataPayload) ProtoMessage() {}

func (x *AppDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_meshchat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDataPayload.ProtoReflect.Descriptor instead.
func (*AppDataPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_meshchat_proto_rawDescGZIP(), []int{3}
}

func (x *AppDataPayload) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *AppDataPayload) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AppDataPayload) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

var File_internal_protocol_meshchat_proto protoreflect.FileDescriptor

var file_internal_protocol_meshchat_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xd9, 0x02, 0x0a,
	0x0a, 0x4d, 0x65, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x74, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x04,
	0x69, 0x6e, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00,
	0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x48, 0x00, 0x52, 0x07, 0x61, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x50, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x70, 0x68, 0x65, 0x6d,
	0x65, 0x72, 0x61, 0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x50, 0x0a, 0x0b, 0x52, 0x65,
	0x73, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x70, 0x68,
	0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x72, 0x0a, 0x0e,
	0x41, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74,
	0x2a, 0x6b, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17,
	0x0a, 0x13, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x43, 0x4b, 0x45,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a,
	0x10, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x03, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x63,
	0x68, 0x61, 0x79, 0x6a, 0x61, 0x69, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x63, 0x68, 0x61, 0x74,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protocol_meshchat_proto_rawDescOnce sync.Once
	file_internal_protocol_meshchat_proto_rawDescData = file_internal_protocol_meshchat_proto_rawDesc
)

func file_internal_protocol_meshchat_proto_rawDescGZIP() []byte {
	file_internal_protocol_meshchat_proto_rawDescOnce.Do(func() {
		file_internal_protocol_meshchat_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protocol_meshchat_proto_rawDescData)
	})
	return file_internal_protocol_meshchat_proto_rawDescData
}

var file_internal_protocol_meshchat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_meshchat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_protocol_meshchat_proto_goTypes = []interface{}{
	(PacketType)(0),        // 0: protocol.PacketType
	(*MeshPacket)(nil),     // 1: protocol.MeshPacket
	(*InitPayload)(nil),    // 2: protocol.InitPayload
	(*RespPayload)(nil),    // 3: protocol.RespPayload
	(*AppDataPayload)(nil), // 4: protocol.AppDataPayload
}
var file_internal_protocol_meshchat_proto_depIdxs = []int32{
	0, // 0: protocol.MeshPacket.type:type_name -> protocol.PacketType
	2, // 1: protocol.MeshPacket.init:type_name -> protocol.InitPayload
	3, // 2: protocol.MeshPacket.resp:type_name -> protocol.RespPayload
	4, // 3: protocol.MeshPacket.app_data:type_name -> protocol.AppDataPayload
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_protocol_meshchat_proto_init() }
func file_internal_protocol_meshchat_proto_init() {
	if File_internal_protocol_meshchat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protocol_meshchat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeshPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protocol_meshchat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protocol_meshchat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protocol_meshchat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDataPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_protocol_meshchat_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MeshPacket_Init)(nil),
		(*MeshPacket_Resp)(nil),
		(*MeshPacket_AppData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protocol_meshchat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_meshchat_proto_goTypes,
		DependencyIndexes: file_internal_protocol_meshchat_proto_depIdxs,
		EnumInfos:         file_internal_protocol_meshchat_proto_enumTypes,
		MessageInfos:      file_internal_protocol_meshchat_proto_msgTypes,
	}.Build()
	File_internal_protocol_meshchat_proto = out.File
	file_internal_protocol_meshchat_proto_rawDesc = nil
	file_internal_protocol_meshchat_proto_goTypes = nil
	file_internal_protocol_meshchat_proto_depIdxs = nil
}
